CREATE TABLE IF NOT EXISTS `b_seat_reservation` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `gmt_create` datetime NOT NULL,
  `gmt_modify` datetime NOT NULL,
  `seat_row` varchar(2) NOT NULL COMMENT '座位行号，例如A-H',
  `seat_number` int(11) NOT NULL COMMENT '座位号',
  `seat_code` varchar(16) NOT NULL COMMENT '座位编码，例如A6',
  `name` varchar(128) NOT NULL COMMENT '预约人姓名',
  `email` varchar(255) NOT NULL COMMENT '预约人邮箱',
  `phone` varchar(64) NOT NULL COMMENT '预约人电话号码',
  `ip` varchar(64) NOT NULL COMMENT '预约请求IP',
  `consultant_name` varchar(128) NOT NULL COMMENT '顾问姓名',
  `consultant_code` varchar(64) NOT NULL COMMENT '顾问记录code，由顾问次数生成，从01开始',
  `consultant_sequence` int(11) NOT NULL COMMENT '顾问第几次记录，从1开始',
  `poster_url` varchar(255) NOT NULL COMMENT '本次预约随机生成的电影海报路径',
  `ticket_image_path` varchar(512) DEFAULT NULL COMMENT '查询页面展示的完整票根图片路径',
  `email_image_path` varchar(512) DEFAULT NULL COMMENT '邮件发送的独立海报图片路径',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_b_seat_reservation_seat_code` (`seat_code`),
  UNIQUE KEY `uk_b_seat_reservation_email` (`email`),
  UNIQUE KEY `uk_b_seat_reservation_phone` (`phone`),
  UNIQUE KEY `uk_b_seat_reservation_consultant_sequence` (`consultant_name`, `consultant_sequence`),
  KEY `idx_b_seat_reservation_gmt_create` (`gmt_create`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='座位预约记录表';
